### ISSUE TITLE
==> arm: Unknown host QEMU_IFLA type: 50

### ISSUE THREAD

**Issue by BaptisteAmato** [mkaczanowski/packer-builder-arm#47] opened 2020-08-27 09:12 UTC
Hi,

I get several erros like this one during provisioning:
`
==> arm: Unknown host QEMU_IFLA type: XXX
`

Any idea where it comes from?

**Comment by mkaczanowski** [comment] 2020-08-27 10:54
those are the qemu binfmt messages

**Comment by BaptisteAmato** [comment] 2020-08-27 13:11
Does it mean everything related to qemu binfmt is about the image I'm building? I'm having a hard time understanding where the commands come from, the host or the newly created image...

**Comment by mkaczanowski** [comment] 2020-08-27 21:13
packer-builder-arm chroot's to the image, so it's always a host (in a sense, there is no virtualization). binfmt + qemu is just a way to emulate different CPU architecture.

The problem is somewhere with your qemu or smth system related (not packer-builder-arm related) thus closing

**Closed by mkaczanowski** 2020-08-27 21:13 UTC
